name: Deploy MATH GAME

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # SSH 키 설정
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SERVER_SSH_KEY }}
        known_hosts: unnecessary
        if_key_exists: replace

    # Known Hosts 설정
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

    # Python 설정
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Python 의존성 설치
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    # 서버에 배포
    - name: Deploy to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "app.py,requirements.txt,static/*,templates/*,rankings.json"
        target: "/home/honghyungseok/math-game"
        strip_components: 0

    # 서버에서 서비스 재시작
    - name: Restart Services
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # Python Flask 서버 프로세스 종료
          cd /home/honghyungseok/math-game
          if [ -f flask-server.pid ]; then
            pid_flask=$(cat flask-server.pid)
            kill $pid_flask || true
            rm -f flask-server.pid
          fi

          # Python Flask 서버 시작 및 PID 기록
          nohup python app.py > flask.log 2>&1 &
          echo $! > flask-server.pid
          disown